# Generated by Django 2.0.4 on 2018-04-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='units',
            field=models.CharField(choices=[('g', 'gramm'), ('tbsp', 'tablespoon'), ('ml', 'mililiter'), ('l', 'liter'), ('kg', 'kilogramm'), ('', '')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Meduim'), ('H', 'Hard')], default='Easy', max_length=10),
        ),
    ]
