# Generated by Django 2.0.4 on 2018-04-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0002_auto_20180420_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='units',
            new_name='unit',
        ),
    ]
