# Generated by Django 2.0.4 on 2018-04-19 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0007_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('text', models.TextField()),
                ('image', models.FilePathField(match='^IN_\\d+_RP_\\d+.jpg$', path='/images/recipes', recursive=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.FilePathField(default='RP_0.jpg', match='^RP_\\d+.jpg$', path='/images/recipes', recursive=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeinfo.Recipe'),
        ),
    ]
