# Generated by Django 2.0.4 on 2018-04-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0008_auto_20180420_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='image',
            field=models.FilePathField(match='^IN_\\d+_RP_\\d+.jpg$', path='C:/Users/Assem/Desktop/Web/supercook/src/components/css/images', recursive=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FilePathField(default='RP_0.jpg', match='^RP_\\d+.jpg$', path='C:/Users/Assem/Desktop/Web/supercook/src/components/css/images', recursive=True),
        ),
    ]
