# Generated by Django 2.0.4 on 2018-04-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0010_auto_20180420_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='image',
            field=models.FilePathField(match='^ST_\\d+.jpg$', path='C:/Users/Assem/Desktop/supercook/recipe_1/steps'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FilePathField(match='^RP_\\d+.jpg$', path='C:/Users/Assem/Desktop/supercook/recipe_1'),
        ),
    ]
