# Generated by Django 2.0.4 on 2018-04-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0016_auto_20180420_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
