# Generated by Django 2.0.4 on 2018-04-19 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0018_auto_20180420_0532'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instruction',
            unique_together={('recipe', 'image')},
        ),
    ]
