# Generated by Django 2.0.4 on 2018-04-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0022_auto_20180420_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='descriptor',
            field=models.CharField(default=' ', max_length=20, null=True),
        ),
    ]
