# Generated by Django 2.0.4 on 2018-04-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0024_auto_20180420_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='descriptor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
