# Generated by Django 2.0.4 on 2018-04-20 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0028_auto_20180420_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descriptor',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
