# Generated by Django 2.0.4 on 2018-04-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0029_auto_20180421_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['order']},
        ),
    ]
